version: "3"
services:
  pis-kafka-front:
    image: jciarka/pis-kafka-prod-front:0.0.1
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_PRODUCER_BACKEND_URL=http://192.168.0.248:9090/