version: "3"
services:
  pis-kafka-front:
    image: jciarka/pis-kafka-prod-front:0.0.1
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_BACKEND_PROD_URL=http://127.0.0.1:9090/  
      - REACT_APP_BACKEND_CONS_URL=http://127.0.0.1:9091/