apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pis-ingress
spec:
  rules:
  - host: pis.kafka.app.test
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: pis-kafka-prod-service
            port:
              number: 9090
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pis-kafka-front-service
            port:
              number: 3001