apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer-frontend
  labels:
    app: pis-kafka-front
spec:
  selector:
    matchLabels:
      app: pis-kafka-front
  replicas: 1
  template:
    metadata:
      labels:
        app: pis-kafka-front
    spec:
      containers:
        - name: pis-kafka-front
          image: jciarka/pis-kafka-prod-front:0.0.1
          ports:
            - containerPort: 3001
          env:
            - name: REACT_APP_BACKEND_URL
              valueFrom: 
                configMapKeyRef:
                  name: pis-kafka-front-configmap
                  key: backend_url
---
apiVersion: v1 
kind: Service 
metadata:   
  name: pis-kafka-front-service
spec:   
  selector:     
    app: pis-kafka-front  
  # type: LoadBalancer    
  ports:     
    - protocol: TCP
      port: 3001
      targetPort: 3000
      # nodePort: 30000